### ISSUE TITLE
Create black icons set

### ISSUE THREAD

**Issue by nathos** [primer/keynote-octicons#1]
It'd be great to have a set of black icons as well…

@jonrohan were these created from a PDF export from Sketch? Any other automation involved?

**Comment by jonrohan** [comment]
@sophshep could you add a black version?

@nathos I started hacking on making this more automated, but I couldn't find any great prior-art for 

- converting svg to keynote
- or creating keynote templates programmatically
- or creating powerpoint files programmatically 

Ideally in the future this repo will pull in the svg files from primer/octicons and build the template.

**Comment by nathos** [comment]
@jonrohan I did discover that when using Sketch's "Export Artboards to PDF" from the `octicons-master.sketch` file, it does a create a nice multi-page PDF:

[octicons-master.pdf](https://github.com/primer/keynote-octicons/files/628619/octicons-master.pdf)

Each page can be copy/pasted into Keynote as a vector object.

…but yes, creating the Keynote programmatically seems troublesome. It _might_ be possible with AppleScript, but like most things AppleScript, it looks painful/limited:

```
tell application "Keynote"
	activate
	tell the front document
		tell the current slide
			
			-- TO CREATE A NEW IMAGE ITEM:
			-- use the make command and include an HFS file reference to the file to be imported, as the value of “file” property
			set newImageItem to ¬
				make new image with properties ¬
					{file:alias "Macintosh HD:Users:sal:Pictures:NASA Rocket.jpg"}
			
		end tell
	end tell
end tell
```

(via [Sal Soghoian's iworkautomation.com](https://iworkautomation.com/keynote/image-placeholder.html))

**Comment by jonrohan** [comment]
The problem with just dropping them into keynote from sketch is when it's converted to pdf, there's no way to change the color. Which makes it sucky because we'll have to create a template for every color.

Ideally if we could import them as "symbols" which are keynotes version of scalable graphics. Then we can change the color within keynote.

The apple script approach is interesting, haven't looked at that yet.

Through some deep deep digging, I discovered that the latest powerpoint does import svg properly! And keynote has the ability to open powerpoint files. 🤔

**Comment by sophshep** [comment]
@nathos I've updated the octicons in this repo so the keynote file has both black and white versions that can be copied & pasted.

**Comment by sophshep** [comment]
> were these created from a PDF export from Sketch? Any other automation involved? 

I just copied and pasted them over from the sketch file directly. A pain in the butt since you need to do each one individually, but ultimately much faster than researching and building any scripts.
